### ISSUE TITLE
Not work for me... help

### ISSUE THREAD

**Issue by proyectosanandres** [skeelogy/ifc-ar-flood#2]
Hi there. 
Same happens to me. I download the project and uploaded it to my hosting but I can not see anything more than labels and spaces are left blank. Could tell me what is the error? I tried it in Chrome and Firefox and does not work. 
The rpoyecto uploaded it to: 
http://proyectosanandres.com/arprojects/nuevo2/ 
http://proyectosanandres.com/arprojects/nuevo3/ 

Please watch it.﻿

Thank you﻿

**Comment by skeelogy** [comment]
This is caused by absolute paths to the `js`, `css` and `resources` folders in my old codes.

Can you update your codes to the latest and checkout from the master branch. I have made all the paths relative in that main branch. Load `tests/threejs_skarf_jsartoolkit.html` or `tests/threejs_skarf_jsaruco.html` from a web server to run the appropriate augmented reality tests using a webcam.

For a simpler workaround, you can just move these folders to the root directory in your web server:
- js
- css
- resources

For example, for the `resources` folder, instead of it being in http://proyectosanandres.com/arprojects/nuevo2/resources, move it to http://proyectosanandres.com/resources.

I noticed that you are using old codes so I'd recommend that you use the first method to get the latest version of everything.

**Comment by proyectosanandres** [comment]
Hello and thank you very much for your help. 
I'm lost ... where I find the latest version of the codes? 
Thanks again

**Comment by skeelogy** [comment]
I believe you have checked out one of the first few tags (e.g. GSoC_wk_02_end). What is the command that you used to get the source codes from this repository? Are you cloning the repository using shell commands or perhaps some user interface?

**Comment by proyectosanandres** [comment]
hi there, 
just download the ZIP from here: 
https://github.com/skeelogy/ifc-ar-flood/releases/GSoC_wk_11_12_end 
And today I download this: 
https://github.com/skeelogy/ifc-ar-flood/releases/tag/v1.0.1 
Thank you

**Comment by proyectosanandres** [comment]
I'm trying with this URL: 
http://proyectosanandres.com/arprojects/nuevo4/tests/threejs_skarf_jsaruco.html 
and with these markers: 
http://proyectosanandres.com/arprojects/nuevo4/marcadores_r1_c1.jpg 
And the webcam is activated but not displayed 3D models. 
I need to do something like the example of the police car, the house and the park bench but using the webcam. 
Thanks again

**Comment by skeelogy** [comment]
I see, so you have been downloading the zip files. Yes the release 1.0.1 link that you have specified is the latest.

The markers that you are using are for JSARToolKit. If you run `tests/threejs_skarf_jsartoolkit.html` instead, it should work.

Alternatively, you can use the js-aruco markers in `resources/markers/jsaruco` for the current `tests/threejs_skarf_jsaruco.html` file that you are using.

**Comment by proyectosanandres** [comment]
hi there, 
I keep trying ... 
And I saw that I was using the wrong markers .. jeje 
Sorry
This example works fine: 
http://proyectosanandres.com/arprojects/nuevo4/tests/threejs_skarf_jsartoolkit.html
What changes should I do to change the embedded video with a webcam? 
Thank you

**Comment by skeelogy** [comment]
In the HTML file, try changing line 32 to:
`var useWebcam = true;`

**Comment by proyectosanandres** [comment]
yesssssssss
worked perfectly ... you're a genius. 
thank you. 
Two more questions ... 
1 This example should work on any mobile device? 
2 What software do you use to convert 3d models to js format? 
Again ... you're a genius

**Comment by skeelogy** [comment]
Great that it worked :)

Please open another issue if there are additional questions! Just afraid that there are others who might have the same questions but might not find the answers if I type them here at the bottom of this page which starts off with a different issue.

**Comment by proyectosanandres** [comment]
ok.... just one second
