### ISSUE TITLE
body of html not displayed

### ISSUE THREAD

**Issue by codepoetly** [skeelogy/ifc-ar-flood#5]
hi...
my trial html code opens on a browser locally but the body section is not displayed.
Here is the code
<!DOCTYPE html>
<html>
<head align="center">
<title>
Trials Again!!!
</ tile>
</ head>

<body>

<p align="center"> Trying formatting </p>
<p color= " blue"> This is in blue</p>
<p align="center"> one <br />two<br />three<br /></ p>
<p align="right">one<hr />two<hr />three<hr />
<code>
for(i=1;i<10;i++)
System.out.println("This is a trial html doc");
</ code>

</ body>

</html>

Saved it as trialsagain.html
Opening it on crome locally using file path.
Only header is displayed on tab but page is empty.

what is the issue ?

**Comment by codepoetly** [comment]
well its working fine here but when i run it locally on my computer it does not ...

<!DOCTYPE html>
<html>
<head align="center">
<title>
Trials Again!!!
</ tile>
</ head>

<body>

<p align="center"> Trying formatting </p>
<p color= " blue"> This is in blue</p>
<p align="center"> one <br />two<br />three<br /></ p>
<p align="right">one<hr />two<hr />three<hr />
<code>
for(i=1;i<10;i++)
System.out.println("This is a trial html doc");
</ code>

</ body>

</html>

what are the changes i need to make to my computer to accomadate the execution.. or is there reaqlly an issue?

**Comment by codepoetly** [comment]
well it is working fine here but when i try to run it locally on a browser it does not

<!DOCTYPE html>
<html>
<head align="center">
<title>
Trials Again!!!
</ tile>
</ head>

<body>

<p align="center"> Trying formatting </p>

<p color= " blue"> This is in blue</p>

<p align="center"> one <br />two<br />three<br /></ p>
<p align="right">one<hr />two<hr />three<hr />
<code>
for(i=1;i<10;i++)
System.out.println("This is a trial html doc");
</ code>

</ body>

</html>

do i need to make changes to my local settings?
what is the issue?

**Comment by skeelogy** [comment]
Is this a question about a HTML file in this repository, or a custom HTML file of yours?

**Comment by codepoetly** [comment]
well its a custom file... but could you kindly help me here

**Comment by skeelogy** [comment]
Some issues that I can observe:
- Some keywords are typed wrongly e.g. `</tile>` instead of `</title>`
- You have mismatched tags, either not opened or not closed e.g. `</code>` without `<code>`
- You have to use `document.write()` instead of `System.out.println()`
- `<code></code>` tags are not for running codes, they are meant to display text in a preformatted way

I suggest that you look through this page: http://www.w3schools.com/html/html5_intro.asp

This GitHub issues page is meant for issues related to this repository. Please direct general HTML questions to [StackOverflow](http://stackoverflow.com/). You'll get faster and better replies!

Hope this helps!

**Comment by codepoetly** [comment]
Hey thanks a ton LEE.
I surely will go through it.
